spring:
    # redis的配置
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      jedis:
        pool:
          max-wait: -1ms
          max-idle: 8
          max-active: 8
      timeout: 5000ms
      password: # 密码，如果没有的话，不用输入
    # mysql的配置
    datasource:
      url:
      username:
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      initialization-mode: always
      continue-on-error: true
