spring:
  # redis的配置
  redis:
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    # database: 0
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
    timeout: 5000ms
    password: # 密码，如果没有的话，不用输入
  # mysql的配置
  datasource:
    hikari:
      db1:
        jdbc-url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
        username: root
        password: dashu0701
        driver-class-name: com.mysql.cj.jdbc.Driver
      db2:
        jdbc-url: jdbc:mysql://127.0.0.1:3306/test2?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
        username: root
        password: dashu0701
        driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: dashu0701
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    initialization-mode: always
    continue-on-error: true
  # dubbo配置
  dubbo:
    application:
      name: spring-boot-scaffold-dubbo-provider
      registry: zookeeper://localhost:2181
  boot:
    admin:
      client:
        # Spring Boot Admin 服务端地址
        url: "http://127.0.0.1:8000"
#        instance:
#          metadata:
#            # 客户端端点信息的安全认证信息
#            user.name: ${spring.security.user.name}
#            user.password: ${spring.security.user.password}
#  security:
#    user:
#      name: icro
#      password: 123456

management:
  endpoints:
    web:
      #      base-path: /monitor
      exposure:
        # 设置端点暴露的哪些内容，默认["health","info"]，设置"*"代表暴露所有可访问的端点
        include: '*'
  endpoint:
    shutdown:
      enabled: true
    health:
      # 端点健康情况，默认值"never"，设置为"always"可以显示硬盘使用情况和线程情况
      show-details: always
  server:
    port: 7890

# 自定义配置
application:
  name: @artifactId@
  version: @version@
developer:
  name: icro
  website: http://blog.icro.me/
  wechat: lnetmor