server:
  port: 8080
  servlet:
    context-path: /scaffold

spring:
  application:
    name: @artifactId@
  # 配置测试和线上文件
  profiles:
    active: dev
# 配置日志框架
logging:
  config: classpath:log4j2-spring.xml